# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeftTeam', models.IntegerField(max_length=100)),
                ('RightTeam', models.IntegerField(max_length=100)),
                ('Winer', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamId', models.IntegerField(max_length=100)),
                ('TeamName', models.CharField(max_length=100)),
            ],
        ),
    ]
