# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='LeftTeam',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='RightTeam',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='Winer',
            field=models.IntegerField(),
        ),
    ]
