# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helo', '0003_auto_20170625_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='TeamId',
        ),
    ]
