# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helo', '0005_team_teamid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='LeftTeam',
        ),
        migrations.RemoveField(
            model_name='game',
            name='RightTeam',
        ),
        migrations.RemoveField(
            model_name='game',
            name='Winer',
        ),
        migrations.RemoveField(
            model_name='team',
            name='TeamId',
        ),
    ]
