# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helo', '0006_auto_20170626_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='LeftTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_left_team', to='Helo.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='RightTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_Right_Team', to='Helo.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='Winer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_Winner_Team', to='Helo.Team'),
            preserve_default=False,
        ),
    ]
